### ISSUE TITLE
[BUG] Update does not refresh .csv metaData files

### ISSUE THREAD

**Issue by VeroniqueChouinard** [LabeoTech/Umit#38]
**Describe the bug**
The function 'update project' does not refresh the metaDatafile and it makes the window freezes.

**To Reproduce**
1. Change the .csv file of a specific folder because it was not the right one.
2. Project> look for new raw data>Full update
3. Click on the folder >CtxImg

**Expected behavior**
If full update could update for the new metadatafile, it would avoid freezing.

**Additional context**
I found that if I delete either the project (ex: plasticity.mat) or delete the files then restore garbage list, it updates the correct metadata. **However, that's not very practical.**

**Comment by BrunoOFSouza** [comment]
@VeroniqueChouinard , can you attach your *protocol function*?
Thanks

**Comment by S-Belanger** [comment]
This is not really a bug by itself, since the user didn't had all the files in the data folder prior to the first analysis run. 

It will be moved to the enhancement list

**Comment by BrunoOFSouza** [comment]
This issue will be obsolete in the Bipolar version
