### ISSUE TITLE
ImagesClassification ChannelsSort error

### ISSUE THREAD

**Issue by marl1bakker** [LabeoTech/Umit#44]
Hi, 

I get an error when trying to do imagesclassification that I cannot figure out. I'm using a multicamera set-up, and get the following error: 

>> ImagesClassification(pwd, pwd, 1, 1, 0, 0, 'Internal-main');
Recovering stimulation parameters
**************************
Stimulation not detected. 
Sorting images per channels. 
Camera #1. 
Reference to non-existent field 'Exposure'.

Error in ImagesClassification/ChannelsSort (line 300)
            fColor{indC}.tExposure = colors(indC).Exposure;

Error in ImagesClassification (line 200)
    ChannelsSort(imgFilesList, Colors(idx));
 
Could this be because ChannelsSort function is only defined at line 241 but we call it at line 200? 
Also, not sure if it's an error or if you meant for it to be that way, but I can no longer leave out the input arguments for b_IgnoreStim, b_SubROI and chanName. 

It might be something with my set-up rather than your code as well. Could you help me with this?

Best,
Marleen

**Comment by S-Belanger** [comment]
ChannelsSort is a nested function and they are usually implemented at the end of their parent function.

**Comment by S-Belanger** [comment]
The exposure times were not set properly for the multicam option. It is now fixed
