### ISSUE TITLE
BUG : DeltaF/F maps pipeline issue

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#45]
Hi, I'm unable to obtain a DeltaF/F map of calcium imaging acquisitions using the following pipeline configuration. 
![image](https://user-images.githubusercontent.com/116119599/196544045-573b2f4f-0d90-44d6-b9fb-e49ef8e5a9de.png)

When I run the split_data_by_event function using the mergeDirs_in_eventFile function prior to it, it gives out this error message. 
![image](https://user-images.githubusercontent.com/116119599/196544161-5067645c-6bbe-4361-9c1e-db1fc90a439a.png)

The same pipeline finishes if the mergeDirs_in_eventFile function isn't used, however, it gives out strange DeltaF/F maps. The final product is the same whether I use an old acquisition, which used to work, or a new one.
![image](https://user-images.githubusercontent.com/116119599/196544510-d5dfb0ce-d030-44ce-8629-b5e2ee617945.png)

It should look like this. The calcium imaging acquisitions should be separated according to the timed visual stimulations recorded in the event file.
![image](https://user-images.githubusercontent.com/116119599/196546227-b606a1c5-a202-4c78-82c2-8a0e2e9f803c.png)

The acquisitions aren't corrupted, the toolbox does recognize the event used to split the data and I recently updated the Umit toolbox. I don't really know what's happening since it used to work fine. Thank you!

**Comment by BrunoOFSouza** [comment]
Hi, 
there was an issue with the function **normalizeBSLN.** It was fixed in the commit b7bf0cb7051b913325667b808f66d46be37da159
Can you try again and see if it works?

**Comment by C-A25** [comment]
Hi,
I now get a proper DeltaF/F map by using the normalizeBSLN function without merging the event file directions, but the pipeline still similarly fails if the mergeDirs and Split_data functions are used together before creating the Deltaf/F map.

**Comment by BrunoOFSouza** [comment]
Does *split_data_byEvent* still fails when using this pipeline configuration?
![image](https://user-images.githubusercontent.com/72028622/197030642-e9cab047-6fd3-4ad0-9bfd-4aebae74bba1.png)

**Comment by C-A25** [comment]
Yes. Is the pipeline configuration wrong?

**Comment by BrunoOFSouza** [comment]
No. Just trying to figure out what is wrong... 
I'll need to run some tests. Give you a feedback tomorrow.

**Comment by C-A25** [comment]
Ok, thank you!

**Comment by BrunoOFSouza** [comment]
I made some changes to the code and tested both pipeline configurations. The only thing is that I don't have the reflectXY function (custom fcn). Nonetheless, this fix should work (commit 937dc51471f9b6403d6e9ee2d9634cc826140d2a). 
Let me know if it still bugs.

**Comment by C-A25** [comment]
I tried with one acquisition and it worked. Thank you!
