### ISSUE TITLE
Correlation matrices do not correspond to seed pixel correlation maps

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#46]
When using the following configuration pipelines with identical parameters, the correlation matrix obtained from the same calcium imaging acquisition do not correspond to its respective seed pixel correlation map. The same issue arises with all types of correlation matrices (centroid, avg, etc.).
![image](https://user-images.githubusercontent.com/116119599/197044675-c680566e-e36d-4bdb-a1b7-544e6b6af258.png)
![image](https://user-images.githubusercontent.com/116119599/197044689-d9f9faca-d34d-4885-ad93-edb2ccbdbf76.png)

The SPCM indicates an absence of correlation while it remains strong with the avg_vs_avg correlation matrix (ex. V1right vs V1left).
![image](https://user-images.githubusercontent.com/116119599/197047033-44418b9a-6b3f-47aa-ad23-3a666231a59f.png)
![image](https://user-images.githubusercontent.com/116119599/197045833-86d4c43d-f879-421f-ba18-9cca897a268f.png)

**Comment by BrunoOFSouza** [comment]
Hi, 
I compared the correlation values from both the SCPMap and the correlation matrix and everything seems fine. All 3 algorithms work. 
Here is an example where I created ROIs with 1 pixel each and created the correlation matrix with **centroid_vs_centroid** option:

[SPCM_vs_CorrMat.pdf](https://github.com/LabeoTech/Umit/files/9841260/example_issue46.pdf)

As you can see, the correlation values are the same in both the SPCMap (viewed using the *DataViewer* app) and the correlation matrix (viewed with the *Plot Correlation Matrix* app).  
___
*Are you sure that this is not just a matter of color scale on your images?*

If you think that this is not the case, please share the SPCMap.dat/.mat files as well as the CorrMat.mat file, so I can take a look.

Thanks
