### ISSUE TITLE
run_HemoCompute function directory

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#47]
Hi, 
The run_HemoCompute function searches for files (ex. yellow.mat or AcqInfos.mat) in the raw data folder instead of the saved analysis folder. It cannot read files when they are in the saved analysis folder. 
![image](https://user-images.githubusercontent.com/116119599/197077089-677193a9-6aec-4842-84df-ad07b3378ddb.png)

This pipeline configuration works fine when the files were moved to the raw data folder, but it just isn't the right one. 
![image](https://user-images.githubusercontent.com/116119599/197077119-90575a6f-ba20-4aa6-a9e9-bdc86d8261c5.png)

Thank you!

**Comment by BrunoOFSouza** [comment]
Thanks for pointing out! Fixed on commit 5125951eccec259b7ae5d205463f05c4f43694a2
