### ISSUE TITLE
Extraction of Mean Data Generates Error[BUG]

### ISSUE THREAD

**Issue by evernerve** [LabeoTech/Umit#48]
**Describe the bug**

After opening the vpixx file and selecting the areas of interest in the ROI, if we try to extract that data, selecting the mean option produces an error. However, it works fine with the median option.

**To Reproduce**

After opening the vpixx file and selecting the areas in the ROI
1. Go to 'Utilities'
2. Click on 'ROI options'
3. Click on 'Extract data from ROI'
4. Select 'mean'
5. See error

**Expected behavior**
Expected window to appear where you can select the save folder

**Screenshots**

![image](https://user-images.githubusercontent.com/115589140/198362968-8f2ac007-95f0-4091-95bf-9214a043ee2e.png)

**Comment by BrunoOFSouza** [comment]
Fixed in commit 7f66ec02af66c7662038a71f5fd0f05bf22ab7c5. 
Thanks!
