### ISSUE TITLE
[BUG] - Events file not generating

### ISSUE THREAD

**Issue by Zak-Eckert** [LabeoTech/Umit#49]
Events file upon running run_ImageClassification is not currently working. 

Running task # 1/6 ----->>>>>
	Function Name: run_ImagesClassification 

Recovering stimulation parameters
**************************
Missing triggers in channel StimAna2!
Checking stim info...
No Stimulations detected. Resting State experiment?
Sorting images per channels. 
Sorting img_00000.bin.
Sorting img_00001.bin.
Sorting img_00002.bin.
Sorting img_00003.bin.
Done. 
Warning: Stim signal not found! Skipped Event file creation. 

Then when reaching a point of splitting by event, the error becomes a haulting factor. 

{'Error using split_data_by_event (line 41)↵Event file ("events.mat") not found in  ....

Also of note, this is not an Aux/main stimulation issue, as this was run using an Aux channel, but then when swapping to a main stim channel analysis it gave a different error 

{'Unrecognized field name "Freq".↵↵Error in genEventsFromStimParameters (line 38)

Let me know if there is anything more I can do to help!

**Comment by BrunoOFSouza** [comment]
Hi Zachary, 

Can you send to my e-mail a link to this data?

Thanks!

**Comment by BrunoOFSouza** [comment]
Hi @Zak-Eckert , 

There were some errors in the function *genEventsFromStimParameters*. They were fixed in commit aedab82da209967733d8e2b884c456d232ff7c9f. 
I tested with your data and it works fine now. 

Thanks for pointing out this issue!
