### ISSUE TITLE
run_ImagesClassification function error

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#50]
Hi, the run_ImagesClassification function doesn't work with any type of data. The same error message appears everytime, making it impossible to analyse newly acquired data. 

![image](https://user-images.githubusercontent.com/116119599/201395739-e923f291-9d85-4bcc-81d9-7a5cf1b71428.png)
![image](https://user-images.githubusercontent.com/116119599/201395753-1aaeb543-787d-4e7a-9b1c-eca11215f493.png)

Thank you!

**Comment by BrunoOFSouza** [comment]
@C-A25 , Can you click on the link to the 'ImagesClassification' function and show here the list of the input arguments, please?

**Comment by C-A25** [comment]
![image](https://user-images.githubusercontent.com/116119599/201400086-95d77ccc-569f-4c1d-86ed-992a1b56e5eb.png)

**Comment by BrunoOFSouza** [comment]
@C-A25 , This is an old version (deprecated) of the *ImagesClassification* function. Be sure to remove from Matlab's path any other folder containing deprecated code. 

You can run the function *Umitoolbox_setup* (available from release **Astrocyte v.1.2.4** and above). It will automatically remove any old code in folders containing the string *ioi_ana*. 
Then, try to run the pipeline again. This should fix the issue.
