### ISSUE TITLE
[BUG] misrepresentation of data in the level of contrast ?

### ISSUE THREAD

**Issue by evernerve** [LabeoTech/Umit#51]
hello everyone,
I am performing measurements on the amplitude-median for five levels of contrast. Previously, I had been using four levels of contrast at 30%, 50%, 75%, and 100%, and the order of increasing levels was from 30% to 100% in the conditions part. Recently, we added a 0% contrast level, which has resulted in the levels being arranged in a different order: 30%, 50%, 75%, 0%, and 100%.

I am interested in understanding whether the addition of the 0% contrast level and the change in the order of levels would affect the amplitude-median values. In other words do you think also the result (amplitude-median) in this case changed too or it has the same order just its problem with presentation.
Thank you for your time and consideration. I look forward to hearing from you soon.

Sincerely,

As the contrast value increases amplitude-median also increases but in the current state, at 0%, when there is no expectation of activity, there is more activity than 30 and 50% for this reason I think the order should be like 0 30 50 75 and 100.

<img width="259" alt="Screenshot 2023-01-12 135400" src="https://user-images.githubusercontent.com/115589140/212155243-07a32c4f-d839-476c-85c7-1f88bf95052d.png">

**Comment by BrunoOFSouza** [comment]
@evernerve .  You were right. There was an error in the event ordering in your custom function **genVpixxEventFile**. 
I'll send you the fixed file soon.

P.S.: In the near future we will attempt to create a better way of handling event files from different sources (i.e. Vpixx, PsychoToolbox, PsychoPy etc.).
