### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Zak-Eckert** [LabeoTech/Umit#52]
Greetings,

I had an idea that the UMIToolbox could have an autoscale function in order to correct for differences amongst image scale. For example, this could be a tool in the pipeline configuration that would correct for differences in forsay acquisition binning, This could prove useful for those who are attempting to do any map averaging for group data visualization, as currently there is no automatic/simplistic way to adjust for differences in scale. The only loophole currently is to change how you bin your data using the options setting in image classification, but only works in the excess binning, and not vice versa. 

Zachary Eckert

**Comment by BrunoOFSouza** [comment]
Feature implemented in commit 9dbb8f0da86417ddba03e874995d649307fab9f4.
It will be officially available in the next version of umIT.
