### ISSUE TITLE
run_SpeckleMapping Bug

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#56]
Run_SpeckleMapping should produce a cortical blood flow map created from speckle imaging data, but an error occurs instead.

1. run_ImagesClassification (basic parameters)
2. run_SpeckleMapping (basic parameters)
3. See error
{'Undefined function 'prctile' for input arguments of type 'single'.↵↵Error in SpeckleMapping (line 72)↵pOutlier = prctile(DatOut(:), 99);↵↵Error in run_SpeckleMapping (line 26)↵outData = SpeckleMapping(SaveFolder, opts.sType, opts.channel, opts.bSaveMap, opts.bLogScale);↵↵Error in PipelineManager/run_taskOnTarget (line 666)↵

![image](https://user-images.githubusercontent.com/116119599/227005573-bfa10e3e-676e-4fae-99d8-d3b317145303.png)

**Comment by BrunoOFSouza** [comment]
@C-A25 
The issue was fixed in commit 11b5886395d9145a8be13ba43a4a125d8e8d0d95

Thanks!
