### ISSUE TITLE
Save function bug at any time during a pipeline

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#57]
A pipeline will be running smoothly until an error occurs with the Save function. If a pipeline contains 10 items, it can completely fulfill the analysis for the 5 first items and then run into an unsuspected issue at the sixth one out of nowhere. It can fail to save after any function. It happened after using the GSR.m, alignFrames.m and run_HemoCorrection.m functions as well as a full project. The pipeline then stops and the data is considered corrupted even when it isn't. I was once able to properly do the analysis after rebooting the computer or closing matlab, but it came back.

It fails to create and save the .mat file with the .dat file. Consequently, the .dat file cannot be opened anymore using the load function. 

Ex. of pipeline for a resting state acquisition :
1. Run_imagesclassification
2. Run_hemocorrection - Failed here
3. Alignframe - Failed here
4. NormalizeLPF
5. GSR - failed here
6. SPCM

![image](https://user-images.githubusercontent.com/116119599/230434731-916a9610-9d3e-416c-996d-00b18204f419.png)

**Comment by BrunoOFSouza** [comment]
Hi @C-A25, 

There are several reasons why a .mat file can become corrupt.
Can you check if you have enough space on the Hard Drive? Some times this happens when the HD is almost full. 
Is the HD local or is it remote?
