### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Zak-Eckert** [LabeoTech/Umit#59]
Suggestion for UmIToolbox: 

A feature which might not be useful on an individual researcher level, but might be more useful on conjoint projects or merging of data between individual researchers would be the ability to merge acquisition/analysis data to a shared protocol function. I am aware the limitations still would be that a shared protocol function would need be in place, but it could result in more clean organization of data collection between for say experimental and paper data collecting work. 
By doing so you could therefore keep separate acquisitons, then for analysis merge them together at a later date. Therefore raw data can be organized as such on computers with less storage capabilities, or with multiple pc acquision setups in the potential future. 

Hope this is clear and insightful. 
Zachary Ecker, MSc.

**Comment by BrunoOFSouza** [comment]
Hi @Zak-Eckert , 

Now, the toolbox allows the usage of multiple raw directories (commit e03fe6d56c6ec3779cdabae024ca227b42e7f3fc).  I don't know if this fully answers your request though. 
Feel free to reopen this issue.

Cheers,
