### ISSUE TITLE
[BUG] - Issue with configure Pipeline button interface on GUI 

### ISSUE THREAD

**Issue by Zak-Eckert** [LabeoTech/Umit#64]
I found a bug where for some reason, the Configure Pipeline button does not properly load data anymore. This happened after I added in an extension of my data (so I added in session 2 for each animal) I utilized the button to add new data using an add new data only. And now the Toolbox doesn't permit for the Configure Pipeline button on either old or new data, as well as data with or without raw bin files present. Aka, it completely stopped working. 

I have reset the toolbox and tried to run it as administrator with no success. Unsure what is the root this time around. Let me know your thoughts, 

Zak

Unrecognized field name "ClassName".

Error in umIToolbox/ConfigurepipelineButtonPushed (line
1296)
                if
                ~all(strcmpi(app.PipelineObj.ClassName,
                cellfun(@class, NodeObjList,
                'UniformOutput',false)))
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by BrunoOFSouza** [comment]
Fixed in commit 55374e15e196f6f34fc8a5b4e0cac4308cb6b291

Thanks!
