### ISSUE TITLE
Bug Selecting Large Number of Data in The GUI interface

### ISSUE THREAD

**Issue by Zak-Eckert** [LabeoTech/Umit#66]
Using the most recent update Last friday), I am having an issue where recently I notice that the GUI interface has a particularly difficult time with selecting large number of data 1 at a time in the window.  *see image*

Upon trying to select them, it  used to give a prompt, as in a limiter that would show that the software was rendering in the new selections when trying to do analysis, or pipeline configuration for say. In doing so would be slower to select, but would always select all clicked options 100% of the time. But now, If I am to select multiplt selections from multiple animals (For say, all Session 6 and 7 from all animals as shown in the attachement), then  it will randomly fail to select some of the selected files, and they will return to unselected colour (white). Typically, this occurs after about 2-4seconds after clicking on the  data. 

I'm not sure if there is an easy fix to this, but I thought I would bring it up as it happens when manually selecting mass data points. 

Best, 
Zachary Eckert. Msc.

![image](https://github.com/LabeoTech/Umit/assets/101667936/6552fd20-1439-4668-9fc5-951fb1e15dbe)

**Comment by BrunoOFSouza** [comment]
Hi @Zak-Eckert !
Question: In which tab(s) of the **umIToolbox** this occurs? Is it on the *Dashboard*^

**Comment by Zak-Eckert** [comment]
Greetings, It is version Main (Astrocyte v1.5.6)
Also, this is on the pipeline control panel typically. 
Zak

**Comment by BrunoOFSouza** [comment]
Hi @Zak-Eckert!
Unfortunately, I couldn't replicate the error on my end. The selections of the elements (i.e. nodes)  in the folder tree can be a bit tricky though. 
Basically, in the pipeline control panel, the selection behaves as such:
- All items below the selected node will be automatically selected. 
- To select consecutive nodes, press Shift + left click.
- To select non-consecutive nodes, press Ctrl + left click. 

However, I have a suggestion to unclutter the folder tree. Lets take your example:
If you want to select all recordings **S6** and **S7**, you can use the ***Advanced Search*** button to filter out the other recordings. Check the documentation [here](https://labeotech.github.io/Umit/documentation/userDocs/umIToolbox.html#advanced-search).
In your case, to filter the **S6** and **S7**, select the field ***ID*** on the **Acquisition** box and generate the following query:
`(S6_[ID]) OR(S7_[ID])` ( you can copy/paste this in the **Query** field).  This will show only S6 and S7 acquisitions for all mice. Click on ***Reset Search*** button to show all items. 

I'll let you try this out. 
I'll close this issue, but feel free to reopen it if this bug persists.

Thanks!
