### ISSUE TITLE
[BUG] - Manual Image Registraion Error

### ISSUE THREAD

**Issue by Zak-Eckert** [LabeoTech/Umit#67]
Greetings!

An error in specifically manual image generation has occured using main v 1.5.6.
The Automatic allignment does still work, but upon trying to correct an error, I was unable to generate alligned channel data files. 
The process went as normal, we get the manual image generation, it gives a preview/confirmation tab, then after it renders it the following error code applies (see below). Appears both in the GUI application and in the error code that it is a save folder / data issue. It should be noted this happens on different data sets from different days and animals. 

Thanks for your help!
Zak

Property assignment is not allowed when the object is empty.  Use
subscripted assignment to create an array element.

Error in manual_alignFrames>moveDot (line 223)
dot1.XData = coords(1);
 
Error using linkaxes (line 86)
Error while evaluating Figure WindowButtonMotionFcn.

Not enough input arguments.

Error in genDataHistory (line 29)
                'opts', optsStruct, 'funcStr', {fcnStr},
                'outputFile_list',
                outFileList,'inputFileName',inputFileName);

Error in manual_alignFrames>warpData (line 191)
dtHist = genDataHistory(fcnInfo,['out = manual_alignFrames(object,'''
applyToFile ''');'],...

Error in manual_alignFrames (line 151)
        warpData(tform,refFr,ref_frame_info,Rfixed,SaveFolder,applyToFile,
        outFileName)

Error in umIToolbox/ManualImageregistrationButtonPushed (line 1735)
                b_redo = manual_alignFrames(myObj,
                app.SelectafileListBox.Value);
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 410)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by BrunoOFSouza** [comment]
Hi @Zak-Eckert !

The bug was fixed in the commit a8191e7364e14a5d4fc548a60538ae51f839c335.
Thanks for the bug reports! We appreciate the feedback!
