### ISSUE TITLE
ROI manager - Set colormap option [BUG]

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#71]
**Describe the bug**
An error occurs when selecting the set colormap option in ROI manager. Colormap cannot be modified using this option. 
![image](https://github.com/LabeoTech/Umit/assets/116119599/c2e86e95-5477-4685-85a6-36279a581281)

**To Reproduce**
1. Load any data in ROI manager
2.  Select Image then Set colormap
![image](https://github.com/LabeoTech/Umit/assets/116119599/8cd05393-4a58-4ae7-b767-9ee1ef7137b1)

**Comment by BrunoOFSouza** [comment]
Fixed in commit b673e18e70829d4f4d22e24eb482c79bc3523435
