### ISSUE TITLE
getDataFromROI - ''None'' SpatialAggFcn bug

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#72]
**Describe the bug**
''None'' spatial aggregation option of getDataFromROI function doesn't work when extracting data from ROIs.

**To Reproduce**
1. Exemple - Calculate_Response_Amplitude map (default options)
2. getDataFromROI - Add ROImasks_name and SpatialAggFcn option - None
3. Error
![image](https://github.com/LabeoTech/Umit/assets/116119599/4afac60e-1f69-4828-8985-70ab3d2ecc22)

**Expected behavior**
It should create a .mat document containing ROI data without aggregation. This issue doesn't occur when ''mean'' spatial aggregation is applied.

**Comment by S-Belanger** [comment]
We will be working on this soon. Sorry for the inconvenience

**Comment by BrunoOFSouza** [comment]
Fixed in commit 61d738abaac6018c9b84004af2bf118e10f92fad
Thanks!
