### ISSUE TITLE
Suggestion : Adjustable x-axis values option for line/box plots function

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#73]
**Give your suggestion**
When using the line/box plots function in the Analysis tab, it would be useful if x-axis values could be adjusted to create a scale.

**Visual aid**
![image](https://github.com/LabeoTech/Umit/assets/116119599/2d48f535-3bfb-4880-98bb-bafebe3da7ea)
Ex. Increasing contrasts are represented as categories with a fixed step in between instead of a graduated scale with varying steps. It would improve plots if x-axis values could be adjusted depending on the need. 

Thanks!

**Comment by BrunoOFSouza** [comment]
Feature added in the PlotLongData app (commit 4c85d2305b97ca16da3392eab56d70c25f91779d)
