### ISSUE TITLE
genVSM

### ISSUE THREAD

**Issue by DevilsAdvocate2244** [LabeoTech/Umit#76]
Bipolar v2 0 0 
Hi everyone,

I hope you're all doing well. I'm currently working on retinotopy and utilizing the functions genRetinotopyMaps and genVSM. However, after running genVSM, I encounter an error when I try to use the patches with visualctxareas.

Has anyone experienced this issue or can offer any advice on how to resolve it?

Error using matlab.graphics.primitive.Image/set
Invalid or deleted object.

Error in ROImanager/lockAxChild (line 322)
set(app.imageHandle, 'HandleVisibility', tag);

Error in ROImanager/importROIfromMask (line 1789)
app.lockAxChild("image", true);

Error in ROImanager/importROIsMenuSelected (line 3840)
app.importROIfromMask;

Error using matlab.ui.internal.controller.WebMenuController/fireActionEvent (line 67)

**Comment by BrunoOFSouza** [comment]
Hi, 
Can you describe the steps leading to the error?
This is on ROImanager as add-on on DataViewer, right?

**Comment by DevilsAdvocate2244** [comment]
hi hope you are doing well after runing the pipline i go to roimanager and then go to file->importRoiform->.matfile and open the VisualCtxAreas.mat->patches and error
________________________________

**Comment by BrunoOFSouza** [comment]
Hi, 
Unfortunately, I could not replicate the error on my end. 
Perhaps this bug was already fixed. Could you please update the toolbox to the latest version and try again?

Let us know if it works.

Thanks
