### ISSUE TITLE
AlignFrames function Bug

### ISSUE THREAD

**Issue by C-A25** [LabeoTech/Umit#77]
umiT version : Astrocyte-v1.5

** The issue **
Data were run through run_ImagesClassfication, ManualCoreg2Cams and run_HemoCorrection scripts before using the alignFrames function where the bug occured. Imaging data cannot be aligned due to the bug.

**To Reproduce**
1. run_Images Classification (default options)
2. run_HemoCorrection (no yellow, yes to green and red)
3. alignFrames (error - see screenshots)

**Expected behavior**
Imaging data should be aligned using the imaging reference frame proposed.

**Screenshots**
![image](https://github.com/user-attachments/assets/b4a5c6f2-d9ab-4402-b828-9d39f31ec96e)

Thank you!

**Comment by BrunoOFSouza** [comment]
Hi @C-A25,
Probably the issue comes from the fact that your images contain NaNs.
I modified the alignFrames function to managed that (see commit 06cfcd8b3ac5d76158a22bc1e467843b23c75436) . 
This should fix the problem.
Let us know if it doesn't.

**Comment by BrunoOFSouza** [comment]
Hi @C-A25 ,

Actually, these large patches in the reference and registered masks are the result of a Gaussian filter applied to the images. This filter is not applied to the aligned data.
Also, you just remembered me to apply the same NaN management to the manual alignment as well (see commit 70f6f9fd720f5f407cf39e26ca11bc5002b42c74). 

Thanks!
